server:
  port: 8081
spring:
  application:
    name: "accounts"
  profiles:
    active: "dev"
  config:
    import: "optional:configserver:http://localhost:8072/"

mysql:
  username: "useraaa"
  password: "pass"
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"



