server:
  port: 2003
  gw: http://10.10.10.218
spring:
  application:
    name: vidaptor-data
  data:
    mongodb:
#      host: 10.10.10.218
#      port: 27017
#      authentication-database: admin
#      username: vidaptor
#      password: Cs456321
      auto-index-creation: true
      database: masterdb
  profiles: 
    active: dev
  cloud:
    config:
        uri: http://10.10.10.218:2000

security:
  jwt:
    uri: /api/auth/**
    secret: JwtSecretKey
    header: Authorization
    prefix: Bearer
    expiration: 3600
labSample.defaultPageSize: 5
labOrder.seq.ip: 10.10.10.218
labOrder.api.order: 10.10.10.218

### MAIL SETTINGS
mail.transport.protocol: smtp
mail.smtp.host: mail.drsulaimanalhabib.com
mail.smtp.port: 25
mail.smtp.auth: true
mail.smtp.starttls.enable: true
mail.smtp.ssl.trust: mail.drsulaimanalhabib.com
mail.to: Atif.Umar@cloudsolutions.com.sa;
#disable the schedular
#schedule.cron: -

#every hour
schedule.cron: 0 */2 * * * *

labsample.vida.testdirectory: http://10.201.201.104:8023/vida/test-directory/

cacheaside:
   gw:
     address: http://10.10.10.218/
   auth:
     url: http://10.10.10.218/api/oauth/token/
   upsert-cache-after-fetch: true
   publish-message-when-cache-updated: false
config:
   url: http://10.10.10.218:2000/cacheaside-dev.properties

javers:
  mongodb:
    uri: mongodb://vidaptor:Cs456321@10.10.10.218:27017/audits?authSource=admin

log-viewer:
  server:
    context-path: "/"
  use-web-socket: true
  default-directory: "E:\\LogViewer\\test"
authentication:
  enabled: false
